---
title: "Curriculum Vitae"
page-layout: full
toc: false
format:
  html:
    theme: cosmo
    css: cv-styles.css
    page-layout: full
---

::: cv-container
# Owen Callahan

**PhD in Applied Statistics**\
Bielefeld University

------------------------------------------------------------------------

## Education

::: cv-item
::: cv-left
**PhD Applied Statistics**\
Bielefeld University
:::

::: cv-right
10/2024 – Present
:::
:::

::: cv-item
::: cv-left
**MSc Environmental Psychology**\
University of Groningen
:::

::: cv-right
09/2021 – 02/2023
:::
:::

::: cv-item
::: cv-left
**BS Psychology (Minor: Statistics)**\
Virginia Polytechnic Institute and State University
:::

::: cv-right
09/2017 – 06/2021
:::
:::

------------------------------------------------------------------------

## Professional Experience

::: cv-item
::: cv-left
**UX Researcher**\
Hardt Hyperloop, Groningen, NL
:::

::: cv-right
04/2022 – 11/2022
:::
:::

-   Designed psychometric instruments and latent-class models\
-   Built multivariate regression models\
-   Presented statistical findings to stakeholders

::: cv-item
::: cv-left
**Student Researcher**\
Center for Applied Behavioral Systems, VA
:::

::: cv-right
01/2018 – 05/2021
:::
:::

-   Trained undergraduate researchers\
-   Cleaned data\
-   Designed and validated survey instruments in R\
-   Co-authored research manuscripts

::: cv-item
::: cv-left
**Private Statistics Tutor**\
Self-employed, Groningen, NL
:::

::: cv-right
09/2021 – Present
:::
:::

-   Supported 25+ students in advanced statistical methods

------------------------------------------------------------------------

## Skills

**Software:** R, NetLogo, SPSS, Atlas.ti, Microsoft Office

------------------------------------------------------------------------

## Certifications

**R Programming**\
Johns Hopkins Bloomberg School of Public Health (2023–2024)

**Mathematical Biostatistics**\
Johns Hopkins Bloomberg School of Public Health (2023)

------------------------------------------------------------------------

## Awards

-   Summa Cum Laude\
-   Dean's List\
-   Beyond Boundaries Scholar

------------------------------------------------------------------------

## Conferences

-   Social Simulation Conference (2025, Delft)\
-   UniC Summit (2021, Quebec)\
-   COP25 United Nations Climate Change Conference (2019, Madrid)\
-   Mid-Atlantic Undergraduate Research Conference (2019)\
-   North Carolina Applied Behavioral Association (2019)
:::
