---
title: "Help Page"
format:
  html:
    toc: true
    toc-depth: 3
    code-copy: true
    code-tools: true
    code-fold: false
    smooth-scroll: true
about: 
 template: marquee

---

# Project Files

A Quarto website
has:

-   `_quarto.yml`
    → controls the
    entire website
-   `.qmd` files →
    individual
    pages
-   `images`
    folder → store
    images
-   `docs` folder
    → Github pages
    access (do not
    touch the docs
    folder)
-   `styles.css` →
    styling
    specific pages

If something
changes across the
whole website,
edit
`_quarto.yml`. If
something changes
on one page only,
edit that page’s
YAML.

------------------

# YAML

Every page can
override global
settings.

YAML indentation
MUST use spaces,
not tabs. -
Indentation
defines
hierarchy. - A
misplaced space
will cause errors
for your site.

Useful advanced
options:

-   `draft: true`
    → hides page
    from rendering
-   `freeze: auto`
    → avoids
    re-running
    heavy
    computations
-   `page-layout: full`
    → removes side
    margins
-   `page-layout: article`
    → default blog
    style

------------------

# Styles

To create the CSS
File, click File →
New File → Text
File, and name the
file however you
like but make sure
it ends with
styles.css like
the one in Owen's
template.

To link the
styles.css file to
a page of your
choice, go to the
yml code at the
top of qmd file
and paste the name
of your css file

``` r
format:
  html:
    css: cv-styles.css
```

To learn how the
css code works you
can visit this
youtube link:

[Customize
appearance with
CSS/SCSS](https://www.youtube.com/watch?v=pAN2Hiq0XGs)

------------------

# Images

Always store
images in the
images folder.\
To add an image,
the easiest way is
to first make sure
you are in visual
mode, then click
insert, then click
Figure/Image and
chose the file on
your computer.
